spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:6173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user
          predicates:
            - Path=/u/**
          filters:
            - StripPrefix=1
          uri: lb://user
        - id: demo
          predicates:
            - Path=/d/**
          filters:
            - StripPrefix=1
          uri: http://127.0.0.1:8080
        - id: business
          predicates:
            - Path=/b/**
          filters:
            - StripPrefix=1
          uri: lb://business
        - id: scheduler
          predicates:
            - Path=/s/**
          filters:
            - StripPrefix=1
          uri: http://127.0.0.1:8083